### ISSUE TITLE
Armor's Plus' Arrows can't be shooted

### ISSUE THREAD

**Issue by Lushtub** [SmashingModsTogether/SMT-Issues#1]
**Describe the issue**
Armor's Plus' Arrows can't be shooted. The bow animation is playing, but when it's time to shoot the arrow it just do nothing.

**To Reproduce**
1.Try to shoot any Arrows added by Armor Plus with any bows. Won't work.

**Expected behavior**
They should be able to be shooted.

**Game Environment(please complete the following information):**
- 1.0.2
- Armor Plus

**Comment by Dark-Arcana** [comment]
I've replicated this issue. There aren't any issues reported on the ArmorPlus Github, so there might be some interaction with other arrows or bows in the modpack. Since we already have a huge number of arrows, I'm going to disable and hide these as a "fix".
