### ISSUE TITLE
Server/Singleplayer Crash on Psi Circle Overgrowth Spell Use

### ISSUE THREAD

**Issue by JartanFTW** [SmashingModsTogether/SMT-Issues#10]
**Describe the issue**
Server crash upon use of a Psi circle overgrowth spell.

**To Reproduce**
Note: Skipping instruction to making a wand in Psi. Make one capable of running this spell.
1. Implant the spell from the following link into a circle spell bullet, and put it in a psi wand. https://imgur.com/OnuoFG0
2. Use the spell anywhere.

**Expected behavior**
A 3x3(ish) area around the center of the spell should be bonemealed.

**Screenshots**
https://imgur.com/OnuoFG0

**Game Environment(please complete the following information):**
- Windows 10
- Either 16.0.2.0 (64-bit) or 1.8.0.261 (64-bit) (I'm set to automatic, so it's between those two)
- Modpack Version 1.1.0-lite
- Psi (or addon)

**Additional context**
[2021-11-11-6.log.gz](https://github.com/SmashingModsTogether/SMT-Issues/files/7524036/2021-11-11-6.log.gz)

**Comment by JartanFTW** [comment]
Note: There are other similar overgrowth spells that also cause the crash, however the one provided is the simplest, and therefore will probably be the easiest to narrow down the issue with.

**Comment by JartanFTW** [comment]
Narrowed down the issue some:

Please see screenshots
![no_crash](https://user-images.githubusercontent.com/66337180/141392390-0d5051cd-1a1f-44af-9526-a2dd15a465a2.PNG)
![crash](https://user-images.githubusercontent.com/66337180/141392394-471cff49-c8c6-4cec-9cd1-1c85e1be4506.PNG)

Basically, it seems that the Operator: Random square doesn't declare/define the minimum as 0 without the player setting it, despite it being described to do so.
This means that a **temporary** fix to this crash is to simply have the player set the minimum to zero.
A permanent fix would require the mods code to be edited.

**Comment by Dark-Arcana** [comment]
Here's a little more context: https://pastebin.com/2wTVP0mi

This is an issue with either psi peripherals or psi that would need to be fixed by the mod developers. Please report there and reference this issue for them.

**Comment by Dark-Arcana** [comment]
This issue is getting stale. Can we close it or is there something else that needs to be done?

**Comment by JartanFTW** [comment]
This should maintain open and just left alone till a fix is found, in my opinion.

**Comment by Dark-Arcana** [comment]
That is the definition of a stale issue, especially since it's a bug in the mods not in the modpack.
