### ISSUE TITLE
Refined Pipes cannot input/output through Tesseracts

### ISSUE THREAD

**Issue by Timiryazev** [SmashingModsTogether/SMT-Issues#11]
**Describe the issue**
Connecting a Refined Pipe to a tesseract with active items channel does not work. Pipes will not move items at all.

**To Reproduce**
attach pipe & extractor to a chest, attach tesseract to other side.
Place second tesseract, give matching item channels, attach pipe leading to chest.
Nothing happens

**Expected behavior**
Pipes should push items into & pull them out of the tesseract.

**Comment by Dark-Arcana** [comment]
I'm not 100% sure why it doesn't work. But if you attach a hopper, it works.

![image](https://user-images.githubusercontent.com/6245904/142156965-a095d3f0-97be-4f99-b1b6-0bd0faf59a41.png)

**Comment by Dark-Arcana** [comment]
With a hopper in your hand, shift+right click on the side of the tesseract. Then you can attach the pipe to any face of the hopper. The hopper will fill from the pipe and then input into the tesseract. It's not ideal, but it works.

**Comment by Dark-Arcana** [comment]
I found an explanation about the issue on the Tesseract mods issues. You can actually add a chest or other item handler interface block between the pipes and the tesseract (similar to the hopper above). Hoppers can be slow, but shoving items into a chest wouldn't have the same speed concern as the tesseract will draw from them at full speed.

https://github.com/SuperMartijn642/Tesseract/issues/15#issuecomment-683424656

This isn't something that I can improve upon and has an easy work around. So I'm going to close this issue with the caveat that we need to tell people about how to use the tesseract in the quest related to it.
