### ISSUE TITLE
Enchant books not upgradeable

### ISSUE THREAD

**Issue by Timiryazev** [SmashingModsTogether/SMT-Issues#13]
**Describe the issue**
Enchantments can't be upgraded to the cap. Has been confirmed with Fortune and Unbreaking, may apply to other enchants

**To Reproduce**
Combine two Fortune IV books in an Anvil. They combine into another Fortune IV book.

**Expected behavior**
They should combine to a Fortune V book.

**Comment by Dark-Arcana** [comment]
Those are vanilla enchants and should certainly upgrade. I'm wondering though if apotheosis perhaps breaks this behavior.

**Comment by Timbroglio** [comment]
Quite the opposite, I suspect: Apotheosis on its own allows you to combine vanilla enchants to much higher tiers. I would guess Apotheosis is going through and increasing the level cap, and a different mod is going back through and lowering the cap back down again.

**Comment by Dark-Arcana** [comment]
A lot of our mods add or modify enchants in some way. Most of them don't make any changes to the base enchanting system or to vanilla enchants. Mods off the top of my head that do make those style of changes and could be investigated include:

- Quark (oddities adds the matrix enchanter. Not included and disabled other changes)
- Apotheosis (as you said is probably not the culprit)
- Ensorcellation (adds some overrides to vanilla enchants, but this is mostly to allow them to be used on more items)
- Allurement (tweaks to existing enchants according to the description)

**Comment by Timbroglio** [comment]
I'll do some testing and see if I can figure out what's causing it.

**Comment by Timbroglio** [comment]
Issue is with Charm anvil overrides.
Disabling the anvil changes fixes the issue, and all the changes made are already being applied by other mods anyway.

**Comment by Dark-Arcana** [comment]
Let's leave this open until it's in an update / fix branch and merged.
