### ISSUE TITLE
Genetic Animals not working properly with Woot

### ISSUE THREAD

**Issue by ResonantFlux1** [SmashingModsTogether/SMT-Issues#14]
**Describe the issue**
Mob Shards made from Genetic Animals mobs do not produce any drops in a Woot factory.

**To Reproduce**
Create a Mob Shard using Genetic Animals.
Turn it into a Mob Controller.
Add the Mob Controller to a Woot Factory.
Check the shown loot table.

**Expected behavior**
It should be giving normal drops.

**Screenshots**
![Screenshot (264)](https://user-images.githubusercontent.com/89431693/141669829-cb04ca05-85ec-49cd-b3a9-59e437d48670.png)
*

**Comment by Dark-Arcana** [comment]
Thanks for reporting this issue. I've pulled up the Woot wiki (https://github.com/Ipsis/Woot/wiki/Datapacks-For-Woot) and found that you can add custom drops using datapacks that should resolve all of the current issues with things not dropping as expected.

So we've gotta compile a list of all mobs that aren't doing the correct drops and then add to a datapack.

**Comment by Dark-Arcana** [comment]
When attempting to use the woot command to simulate drops, this stack trace is generated. The game / server doesn't actually crash though.

https://gist.github.com/Dark-Arcana/268fe9d3a9146b4587e0b16821ca9965

**Comment by Dark-Arcana** [comment]
I wrote a script that will replace any mobshard from genetic animals (when kills = 5) with the vanilla variant so that you can use that in the mob factory.
