### ISSUE TITLE
Extra Meltable Diamond Items

### ISSUE THREAD

**Issue by JartanFTW** [SmashingModsTogether/SMT-Issues#15]
**Describe your feature request**
In the game currently exists quite a few diamond items that cannot be melted down (in Tinkers Construct) into raw diamonds. I request that melting recipes for these be added. These items would include:

Diamond Knife (Farmer's Delight) 1 diamond
Diamond Fishing Rod (Aquaculture 2) 2 diamonds
Diamond Hook (Aquaculture 2) 4 diamonds
Diamond Reinforced Shield (Spartan Shields) 4 diamonds
Diamond Tower Shield (Spartan Shields) 4 diamonds
Diamond Dust (Thermal Series) 1 diamond
Diamond Gear (Thermal Series) 4 diamonds
Diamond Grit (Create Crafts & Additions) 1 diamond
Diamond Wolf Armor (RevampedWolf) 12 diamonds (yes... 12...)
Diamond Pillar Helmet (Dungeons Mobs) 2 diamonds (this one is pulled from air, as their is no recipe, but is still obtainable)
Diamond Vindicator Helmet (Dungeons Mobs) 3 diamonds (same as above)
Diamond Smith Hammer (BetterEnd Forge) 4 diamonds

Items that may also be added but I am excluding because I am unsure how easy they are to obtain and therefore accurate amount:
Diamond Mountaineer Axe (Dungeons Mobs)
Heart of Diamond (Quark)

**What problem does your feature solve?**
This makes a lot of diamond tools/items that will be left to rot into a useful source of spare diamonds.

**Implementation**
This should theoretically only take some config adjustment, although I'm not sure how this is done so I could be wrong.

**Screenshots**
N/A

**Comment by JartanFTW** [comment]
More items to include:
Enhanced: Diamond (ArmorPlus) 1 diamond
Enhanced: Diamond Helmet (ArmorPlus) 5 diamonds
Enhanced: Diamond Chestplate (ArmorPlus) 8 diamonds
Enhanced: Diamond Leggings (ArmorPlus) 7 diamonds
Enhanced: Diamond Boots (ArmorPlus) 4 diamonds
Relic Apple (Baubley Heart Canisters) 2 diamonds 2 emeralds (this item is extremely similar to golden apples, which can be melted)
Diamond Fillet Knife (Aquaculture 2) 2 diamonds

Unsure amount items:
Pickarang (Quark) Unsure on amount, since it's dependent on Heart of Diamond and idk for that either as mentioned in original post

**Comment by Dark-Arcana** [comment]
This was discussed in the testing channel and if I remember correctly, we've decided that this won't be an added feature. @Timiryazev can refresh my memory here as he was the one who did the investigating.
