### ISSUE TITLE
Quarry+ Ignores Certain Blocks

### ISSUE THREAD

**Issue by JartanFTW** [SmashingModsTogether/SMT-Issues#16]
**Describe the issue**
The quarry from Quarry Plus seems to ignore some blocks. I'm sure there are more, but a few of these that I have found include:
Prismarine Stairs
Prismarine Slabs
Stone Stairs
Stone Slabs

**To Reproduce**
1. Startup a QuarryPlus Quarry Plus in an area with any of the above listed blocks.
2. The quarry will ignore the listed blocks and not mine them.

**Expected behavior**
The quarry should mine the blocks.

**Screenshots**
![2021-11-15_22 30 10](https://user-images.githubusercontent.com/66337180/141890844-877c1cc7-79a4-4fac-bee3-77a0e05d4230.png)

**Game Environment(please complete the following information):**
- Operating System Windows 10
- Java Version N/A
- Modpack Version 1.1.0
- Mod causing issue if applicable QuarryPlus

**Additional context**
N/A

**Comment by Dark-Arcana** [comment]
This isn't something that I can fix. Report it to the mod developer please.

**Comment by JartanFTW** [comment]
https://github.com/Kotori316/QuarryPlus/issues/150
