### ISSUE TITLE
Fluid Encapsulator Crying Obsidian Recipe

### ISSUE THREAD

**Issue by JartanFTW** [SmashingModsTogether/SMT-Issues#17]
**Describe your feature request**
Add a recipe for the Fluid Encapsulator (Thermal Series) that consumes 400RF, 1,000 mB of water, and 1 block of obsidian, and creates 1 block of Crying Obsidian.

**What problem does your feature solve?**
Currently, there is no way to obtain crying obsidian without finding it spawn naturally in the world. This means that the player has to go out of their way to find this block, which is useful for a number of recipes and aesthetically pleasing for certain builds.

**Implementation**
This can be done via config I believe.

**Screenshots**
N/A

**Comment by Dark-Arcana** [comment]
Please remember that exploration and adventure is a core pillar of this modpack. Requiring you to venture out into the world and find things is kinda the point. You can't automate everything.
