### ISSUE TITLE
Netherite Horse Armor Melting Recipe

### ISSUE THREAD

**Issue by JartanFTW** [SmashingModsTogether/SMT-Issues#18]
**Describe your feature request**
Add a recipe for tinker's construct melting for Netherite Horse Armor, for 7 netherite ingots. This would only work in the Foundry, obviously, and require blazing blood.

**What problem does your feature solve?**
All the metallic horse armor in the game currently has melting recipes other than netherite. This makes it more in-line.

**Implementation**
Configs.

**Screenshots**
N/A

**Comment by JartanFTW** [comment]
Edit: I was mistaken, this should melt down to 1 netherite not 7.

**Comment by Dark-Arcana** [comment]
Hmm! You're right. They all have melting recipes.

**Comment by Dark-Arcana** [comment]
This is added in the next update. Thanks.
