### ISSUE TITLE
Amethyst Arrows aren't craftable

### ISSUE THREAD

**Issue by Lushtub** [SmashingModsTogether/SMT-Issues#2]
**Describe the issue**
Amethyst arrows are added by supplementaries, and upon touching terrain, it will explode into bunch of shards that deal damage. I think a recipe should be added for those as it is a pretty funny and nice feature.

**Game Environment(please complete the following information):**
- 1.0.2
- Supplementaries

**Comment by Dark-Arcana** [comment]
Amethyst arrow doesn't have a recipe in the mod source code either. It also isn't apart of any loot tables. In the Supplementaries config file it's listed under #WIP. So I will just disable it for now, as it isn't finished.
