### ISSUE TITLE
Titles given from quests not appearing in title list

### ISSUE THREAD

**Issue by TheDarkPreacher** [SmashingModsTogether/SMT-Issues#25]
**Describe the issue**
After claiming the title rewards in the questbook, titles do not appear in title list.

**To Reproduce**
1. Complete quest with title reward, claim reward.
2. Open title GUI to apply new title
3. No title available.

**Expected behavior**
Expected the title to be available to apply after claiming the quest reward.

**Screenshots**

**Game Environment(please complete the following information):**
- Operating System: Windows 11
- Java Version: jre-1.8.0_311
- Modpack Version: 1.1.2-hotfix-lite
- Mod causing issue if applicable: Titles or FTB quests

**Additional context**
Add any other context about the problem here. Do you have a crash report / latest.log / debug.log file? Please upload the file and provide a download link or use gist / pastebin. **Do not copy and paste log files into your issue!**.

**Comment by TheDarkPreacher** [comment]
after some research, this bug might be related to this open issue from Titles: https://github.com/Aurilux/Titles/issues/26

**Comment by Timbroglio** [comment]
Yeah, we ran into this one a few times in testing, have you tried earning a title in single player? the ones on the front page of the quests can be done instantly, which should resolve the bug.

**Comment by TheDarkPreacher** [comment]
Yeah, earning the quests in SSP unlocks the titles in SMP. Might add a note to the first quest letting people know that they need to do that for servers.

**Comment by Timbroglio** [comment]
Added information about this bug to the front page of quests for 1.1.3 update
