### ISSUE TITLE
Arrow quest line cannot be started due to dependencies

### ISSUE THREAD

**Issue by TheDarkPreacher** [SmashingModsTogether/SMT-Issues#26]
**Describe the issue**
The Arrows quest line can't be started because one of the dependencies is the Amethyst Arrow quest, which is locked behind the starting quest for the Arrows questline.

**To Reproduce**
1. Open quests, go to equipment quests
2. Click on Arrows, attempt to click checkmark, check dependencies
3. See error

**Expected behavior**
Click checkmark in Arrows questline, start the questline.

**Screenshots**
![image](https://user-images.githubusercontent.com/15058826/143718574-f982c10e-28ad-4054-a65f-f352051f48b1.png)

**Game Environment(please complete the following information):**
- Operating System: Win11
- Java Version: jre-1.8.0_311
- Modpack Version: 1.1.2-hotfix-lite
- Mod causing issue if applicable: FTB Quests

**Additional context**
Add any other context about the problem here. Do you have a crash report / latest.log / debug.log file? Please upload the file and provide a download link or use gist / pastebin. **Do not copy and paste log files into your issue!**.

**Comment by TheDarkPreacher** [comment]
Similar issue with the Axes questline, starting checkmark quest has the Netherite Axe quest as a dependency.

![image](https://user-images.githubusercontent.com/15058826/143718833-5ae518aa-1848-4173-a6a9-051fe67b7205.png)

**Comment by Timbroglio** [comment]
Dependency fixes added to 1.1.3 update .
