### ISSUE TITLE
Suggestion: Make mandrake interchangeable between Witchery and Hexerei.

### ISSUE THREAD

**Issue by TheDarkPreacher** [SmashingModsTogether/SMT-Issues#28]
**Describe your feature request**
Add a tag to the mandrake for both Hexerei and Witchery mandrake root so that the witchery mandrake can be used in crafting recipes for Hexerei, since Hexerei mandrake is extremely rare, even in Hexerei biomes.
**What problem does your feature solve?**
Makes it so you can craft the Hexerei broom.
**Implementation**
Just a recipe tag for mandrake so that either item can be used. Can be done with a bit of code writing in kubejs.

**Screenshots**
If applicable, add screenshots to help explain your feature.

**Comment by Dark-Arcana** [comment]
It's relatively simple to add items to a tag. However, that doesn't automatically add the tag to all of the crafting recipes used by both items. Each recipe would need to be added manually. That may not be an issue if I know all of the recipes and uses. So far as I can tell, the only usage for mandrake root from *both* mods is to make a broom in Hexerei. That's what JEI tells me, but there are probably other usages I do not know about. Is this correct or do I need to know more?

**Comment by Dark-Arcana** [comment]
For now, I will add this.

![image](https://user-images.githubusercontent.com/6245904/147172265-33826367-f6fd-443c-8187-8919340fd60b.png)
