### ISSUE TITLE
Mod additions: Evilcraft

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [SmashingModsTogether/SMT-Issues#29]
**Describe your feature request**
Looking for ways to remove curses from items and more then one enchantment removed at a time. 

**What problem does your feature solve?**
The feature request above is the problem solved by the feature. 

**Implementation**
New mod: Evilcraft https://www.curseforge.com/minecraft/mc-mods/evilcraft

**Screenshots**
n/a

Evilcraft is in Spellbound; one of the features in the mod is using the blood purifier to uncurse items and strip enchantments off using blooks. Also goes moderately well with blood magic.

**Comment by Dark-Arcana** [comment]
Thanks for your suggestion. It's now on our list of mods to be added really soon. We just need to investigate it and see what needs to be done to add it.

**Comment by Timbroglio** [comment]
Added in patch 1.3, including quests
