### ISSUE TITLE
Modded Logs and Planks with missing/incomplete output on woodcutters/sawmills

### ISSUE THREAD

**Issue by Nanianmichaels** [SmashingModsTogether/SMT-Issues#3]
**Describe the issue**
Modded logs and planks will either have no outputs, or just partial outputs, or full outputs, when being ran through the vanilla (Charm) woodcutter, or the Environmental sawmill.

From testing, I have noticed the following:

- Cherry and Maple logs and planks from OTBYG, as well as Runewood logs from Malum and Jacaranda Logs from Abundance, give no output on the vanilla woodcutter.
- Runewood, Cherry and Maple logs output sticks, crafting tables and bowls on the Environmental sawmill;
- Runewood, Cherry and Maple planks output bowls and sticks on the Environmental sawmill;
- Jacaranda logs and planks have expected outputs on the Environmental sawmill.

I'm assuming other logs and planks from those mods will net the same results.

**To Reproduce**
1. Open vanilla woodcutter or Environmental sawmill;
2. Place modded log or plank in the GUI slot;
3. See error

**Expected behavior**
Modded logs and planks outputs are the same (depending on the availability of said output as a crafting recipe, that is) as the vanilla logs and planks, on both the woodcutter and the sawmill.

**Screenshots**
No screenshot necessary.

**Game Environment(please complete the following information):**
- Operating System: W10
- Java Version: 1.8.301
- Modpack Version 1.02 Full
- Mod causing issue if applicable: unknown, probably missing a CraftTweaker tweak.

**Additional context**
Available to test changes, if necessary.

Thanks in advance for looking into this!

**Comment by Dark-Arcana** [comment]
Thanks for reporting this. The reason why recipes aren't added for any modded wood types is because the woodcutter is added by the Charm mod and it only accounts for vanilla wood types. But since you reported it, I will look into adding all of the other wood types to both blocks where they are applicable.

**Comment by Dark-Arcana** [comment]
This feature is done and will be added in the next update!
