### ISSUE TITLE
Pulverizer Recipe for Quartzite Sand

### ISSUE THREAD

**Issue by JartanFTW** [SmashingModsTogether/SMT-Issues#30]
**Describe your feature request**
Add a pulverizer recipe for 1 Quartzite Sand into 1 Nether Quartz (50% chance for a bonus)

**What problem does your feature solve?**
Currently, the only way to convert Quartzite Sand into Nether Quartz is to place and break it similar to gravel turning to flint. This means that the most efficient way to convert Quartzite Sand is using a Refined Storage Constructor and Destructor to repeatedly place and break the sand. This, however, causes **dramatic** fps lag to any player rendering this, making the game irritating to play.

**Implementation**
Recipe addition in configs. Probably can add recipes for this for other methods too. Look at Flint in JEI for examples, such as in an Induction Smelter also, or with a Create crusher or mill.

**Comment by Dark-Arcana** [comment]
I'm adding this in the next update (tomorrow). 1 Quartzite sand into 1 Nether quartz isn't correct. Breaking the block doesn't always give quartz, it gives a chance for quartz. So I'm taking a hint from how thermal handles gravel and making it a 20% bonus chance and 100% chance for white sand. I'm adding this recipe to Thermal and Create. 

This recipe isn't as nice as what you asked for, but it's more in line with the current game recipes and balance.

**Comment by Dark-Arcana** [comment]
![image](https://user-images.githubusercontent.com/6245904/147171457-0eb64699-5704-49a0-907e-e4e6b325d529.png)
![image](https://user-images.githubusercontent.com/6245904/147171480-8896fed7-b73c-47ae-b246-4d3a70acbc5f.png)
