### ISSUE TITLE
quest rewards for items of "create" mod should give related items as rewards

### ISSUE THREAD

**Issue by castillao** [SmashingModsTogether/SMT-Issues#33]
**Describe your feature request**
"similar to how the powah mod quests rewards give related items to the item just crafted"

**What problem does your feature solve?**
would solve create quests not having rewards

**Implementation**
sample rewards would be: 

- for quest of creating a machine => andesite alloy (used in all machines to craft basically)
- - encased fan, mechanical drill, and gearbox for example
- for quests related to fluid handling items => copper ingots or copper casing
- - hose pulley, tank, spout all use copper casing
- "precision" items => brass ingot
- - brass casing, mechanical crafter, mechanical arm,

**Screenshots**
sample of groups of quests that should give rewards
![image](https://user-images.githubusercontent.com/58663073/150617959-3ce0c828-5f0a-4342-89b9-346b5d31e839.png)

**Comment by Timbroglio** [comment]
Thanks for the feedback! It looks like the version that got pushed on the last patch was missing the create rewards, there should have been plenty more than there currently are.
This will be fixed on the next update.
