### ISSUE TITLE
Remove Zetter

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#36]
**Remove the Zetter mod**

Does anyone use this mod? It's nifty and all, but if no one is using it, it's best to remove it as bloat. Discuss below.

**Comment by JartanFTW** [comment]
I'm not artsy what-so-ever, so I have no problems with this being removed. I wasn't aware it was even in the pack. Other people might disagree.

**Comment by Dark-Arcana** [comment]
If no one mentions using it in the next few days, I'll just (sadly) remove it.

**Comment by Dark-Arcana** [comment]
Yeah I've decided it stays.
