### ISSUE TITLE
Remove Potion of Bees

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#37]
**Remove the Potion of Bees mod**

I love this mod. It's hilarious. It's fun. But outside of the gimmick of throwing bees at your friends and enemies alike, it doesn't provide anything useful. It's not really bloat either, but it makes the list of mods longer and more daunting to look at xD. Discuss below.

**Comment by JartanFTW** [comment]
I wasn't aware this was in the pack, and therefore have never used it. I think that while it's a nice funny thing to have, the joke dries after a few moments and really isn't worth having the extra mod for.

**Comment by Dark-Arcana** [comment]
Yeah that's certainly true. Also, from what I've learned about KubeJS, I can just make a custom item that does the exact same thing. It was fun to throw bees at people for a while. But they always got mad at me.

**Comment by Timbroglio** [comment]
Schools of Magic has a bees spell.
So, you can remove this *and* throw bees at people

**Comment by Dark-Arcana** [comment]
OH! OH OH. It's gone already lmao.

**Comment by Dark-Arcana** [comment]
Removed.
