### ISSUE TITLE
Replace "My Server is Compatible" with similar mod

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#38]
The mod titled "My Server is Compatible" is great for getting rid of the red "X" next to a server when Forge has issues syncing the modded info between server and client. The red X makes a player think that it's not compatible and they may not even try to join. However this mod breaks the entire thing and allows a player to join a server even when mods are not the same! This is very bad behavior. We need to replace this mod with one that just removes the X. Perhaps a custom menu using Fancy Menu would even work.

**Comment by JartanFTW** [comment]
> However this mod breaks the entire thing and allows a player to join a server even when mods are not the same!  

!! This definitely needs to be changed.

**Comment by Dark-Arcana** [comment]
Yeah, I discovered this when Leah joined the official server with the wrong version. But I was too lazy to do anything about it (re: burnt out).

**Comment by Timbroglio** [comment]
If I may propose an alternative: https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker

**Comment by Dark-Arcana** [comment]
Perfect Tim, this is actually the mod I was going to switch to.

**Comment by Dark-Arcana** [comment]
Replaced.
