### ISSUE TITLE
Remove Tool Belt

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#39]
**Describe your feature request**

Is anyone using the Tool Belt mod? Discuss below.

**Comment by JartanFTW** [comment]
I attempted to use this in my play-through, but it seemed weird to use and more effort than it was worth. I prefer just using a backpack.

**Comment by Dark-Arcana** [comment]
Yeah I was thinking the exact same thing. It's like a wonky and limited backpack.

**Comment by Timbroglio** [comment]
This mod is fantastic, I don't know what you two are talking about
It's a *fast swap* tool solution. I keep everything in it.

**Comment by Dark-Arcana** [comment]
That's all I needed to know. It's a small and simple mod. So as long as anyone is using it, it stays in.
