### ISSUE TITLE
Remove Fishing Real

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#40]
**Describe your feature request**

This mod makes it so that when you fish, a real fish mob is spawned on your hook. You then have to beat the fish to death or pick it up with a bucket of water. I think this adds the ability to access fish easier without having to swim all over the place with a bucket specifically for decoration. But it's such a niche mod that I don't know if anyone is using any of these features. Discuss below.

**Comment by JartanFTW** [comment]
While this is cool, I feel like this is more for a roleplay-esc modpack. This doesn't really add anything mechanically to the game, and is just bloat imo.

**Comment by Dark-Arcana** [comment]
Sadly, yes.

**Comment by Timbroglio** [comment]
Right on the fence between "Cute" and "Frustrating" IMO

**Comment by Dark-Arcana** [comment]
Gotta tip you over and see which side you fall on.

**Comment by TrippNessa** [comment]
The pufferfish poisoning me while trying to fish is enough for me to hate this mod.

**Comment by Dark-Arcana** [comment]
That's hilarious. xD

**Comment by Dark-Arcana** [comment]
> The pufferfish poisoning me while trying to fish is enough for me to hate this mod.

Don't worry, I'm removing it now.
