### ISSUE TITLE
Remove ComputerCraft and addons

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#41]
**Describe your feature request**

ComputerCraft is super niche in that you need to be a programmer and that you have to have a use case for programmable automation. Since this isn't a tech and automation heavy modpack, there probably isn't a very good reason to use this mod. If CC:Tweaked is removed, the addons would also be removed. 

Are you using this mod? Discuss below.

**Comment by JartanFTW** [comment]
I was planning on learning to use ComputerCraft, but despite this, I don't think the mod fits well with the pack and doesn't have very many uses.

**Comment by Timbroglio** [comment]
I like the idea, but barely use it. Incredibly unfriendly to beginners, and I do feel like we had this pack as a "beginner" pack, so, probably worth axeing.

**Comment by Dark-Arcana** [comment]
However, potentially worth having in a more expert style pack, maybe. But even still it might just not have a place in any of our packs. This removed like 5 mods.

**Comment by Dark-Arcana** [comment]
Removed.

**Comment by iarspider** [comment]
Hi! Could you please keep CC and it's addons? You can make it somewhat optional (i.e. remove the quests), but for me it's much easier to use than PnC drones!

**Comment by Dark-Arcana** [comment]
Hello! We've opted to remove it already, and it is removed already in the upcoming release. You are welcome to add it yourself into your own modpack profile. It's pretty easy to do. Pop into the discord and ask if you need help and we will tell you how.
