### ISSUE TITLE
Remove Realistic Horse Genetics

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#42]
**Describe your feature request**

Unlike the Realistic Genetics mod, this mod doesn't add any mechanics for breeding, drops, etc. It just adds the ability to get random horse colors. That being the case, it's not super useful. Should we remove this?

**Comment by JartanFTW** [comment]
Like the other proposed mod removals, this sort of doesn't add much to the pack.
Along with this, you could theoretically just spawn unlimited horses (and therefore different colors) with a spawner.

**Comment by Dark-Arcana** [comment]
Yeah exactly.

**Comment by Dark-Arcana** [comment]
Removed.
