### ISSUE TITLE
Remove Nicephore

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#43]
**Describe your feature request**

This mod adds an easy to use in game GUI to look at your screenshots and copy them for sharing (like for Discord or social media). It also makes a jpg conversion of your screenshots. However, this makes exporting the profile more tedious as you have to manually unselect the nicephore folder inside the mods folder or it will be rejected by CurseForge. I use this mod specifically when taking screenshots and sharing them, but if no one else is really using it or even knows about it, it's best to remove as bloat.

Discuss below.

**Comment by JartanFTW** [comment]
I actually much prefer using Nicephore over figuring out where my screenshots are manually since don't want to go digging for where my twitch install is every time I want to post a quick screenshot to discord.

**Comment by Timbroglio** [comment]
Seconded. The filters are cute and fun, and it doesn't seem like a resource-intensive mod, so it's not contributing much to bloat.

**Comment by Dark-Arcana** [comment]
The filter you mentioned are from Quark, not Nicephore. But I'm glad you both think we should keep it. It's just annoying when you make an export. As long as people are using it! Should we close this?
