### ISSUE TITLE
Remove "More Minecarts and Rails" mod

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#44]
**Describe your feature request**

This mod adds exactly what its title says. Is anyone using this mod? We didn't even make quests for it lol. Discuss below.

**Comment by JartanFTW** [comment]
I think this should be left, as a major playstyle for some private-server players is to build nether rail hubs and things like that.
On the other hand, we do have waystones which defeats the entire purpose- but it's really up to the player to decide what they want to use.
I would leave this one as it does still add a lot to the game that people can choose whether or not to use.

**Comment by Dark-Arcana** [comment]
Yeah that was why I originally added it. Flying is one thing, but nothing beats whipping around on your custom coaster. So I'll leave this. Just wanted some input, thanks!
