### ISSUE TITLE
Remove "Fish in Planks"

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#45]
**Describe your feature request**

This mod is basically entirely useless lol. It adds a handful of blocks that can be crafted to store fish. My original thinking was that it could be cool for some builds. But it's honestly not worth keeping. Thoughts?

**Comment by Timbroglio** [comment]
I didn't even know we had this one. I'd ditch it.

**Comment by Dark-Arcana** [comment]
Agreed.

**Comment by Dark-Arcana** [comment]
Removed.
