### ISSUE TITLE
Remove Grapple Hooks

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#46]
**Describe your feature request**

Does anyone use the grapple hooks mod? They seem like a fun traversal tool. But there are a bunch of other more commonly used tools. Discuss below.

**Comment by Timbroglio** [comment]
There are, like, 8 different ways to fly that are *easier* to access than making a grapple hook is.

**Comment by Dark-Arcana** [comment]
Yeah, unfortunate but needs to be removed. This discussion will need to be had at some point as well, but we need to also remove all quests for these mods.

**Comment by Timbroglio** [comment]
Removing the quests is actually the easy part. Once we've finished the mod updates, I can do a clean-up pass.

**Comment by Dark-Arcana** [comment]
Ahh right right.

**Comment by Dark-Arcana** [comment]
Removed.
