### ISSUE TITLE
Remove "Pretty Beaches"

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#47]
**Describe your feature request**

This mod creates a water source when removing a block from next to another water source in a river or other water biome. The purpose is so that water doesn't get all messed up when digging for sand or gravel from a beach. Keeping this mod is purely aesthetic while it provides an obvious imbalance in that you can cheese it to get infinite water sources automatically. Should we remove it?

**Comment by Timbroglio** [comment]
I mean... minecraft already gives you infinite water sources. I like this because there aren't gaping holes left when I go quarrying sand.

**Comment by Dark-Arcana** [comment]
That's why I added it and like having it. I hate those gaping holes. Creepers are also the worst. We could spin it as a performance feature because there aren't a ton of flowing water blocks when you dig some sand.

**Comment by HolyPoseida** [comment]
I like this idea, because I too despise the horrible broken water on a beach that’s been dug around in, but I must admit, I never noticed it working. I had to fix some broken holes manually. Maybe the way the holes appeared messed with the formation of the water sources, but I never once got this to work.

**Comment by TrippNessa** [comment]
I hate those stupid holes. Anything that helps is fine by me. Let there be easy water.

**Comment by Dark-Arcana** [comment]
hahaha I hear you. Let's close this issue and keep the mod.
