### ISSUE TITLE
Add PneumaticCraft: Repressurized

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#49]
**Describe your feature request**
Let's investigate adding [this mod](https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized) to see if it fits.

**What problem does your feature solve?**

We've just removed a handful of tech related mods. We don't want to severely imbalance the pack where there are far less tech mods compared to magic mods.

**Comment by Timbroglio** [comment]
I feel this one is a good fit. Similar aesthetic to Create, adds a new energy system, and more importantly (IMO) adds tech that's not just material processing. Too many of the tech mods I've been considering just add new processing, and that's not super exciting unless we're making a LOT of custom recipes.

**Comment by Dark-Arcana** [comment]
Yeah I don't know why I didn't originally add it. Do you think this is something you'd be able to make quests for? Most of the other mods we're looking at adding won't need quests.

**Comment by Timbroglio** [comment]
I could do that, would take some time as I don't actually know the mod. Several hours at least, since I have to make sure the quest progression is logical and helpful.

**Comment by Dark-Arcana** [comment]
I figure we won't be adding that this week in either case. Maybe next week?

**Comment by Timbroglio** [comment]
Works for me.

**Comment by Timbroglio** [comment]
Added in patch 1.3, including quests
