### ISSUE TITLE
Blood Magic ritual doesn't activate

### ISSUE THREAD

**Issue by Timiryazev** [SmashingModsTogether/SMT-Issues#5]
The Blood Magic ritual 'Edge of the Hidden Realm" will not activate.

**To Reproduce**
In creative: Spawn items: Master Ritual Stone, Ritual Diviner, Creative Activation Catalyst. Place the stone in a flat area, shift-right-click with the diviner until it says "Edge of the Hidden Realm", then right-click and hold on the Master Ritual stone (it'll build the multiblock around you). Then, take the ritual catalyst, right-click empty air to bind it, then right-click the master stone

**Expected behavior**
The ritual should be struck by lightning and turn into a portal-pillar object.
Currently, it does not.

**Comment by Dark-Arcana** [comment]
Thanks for reporting. Fixed the issue based on your feedback in Discord.
