### ISSUE TITLE
Add Alchemistry

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#50]
Describe your feature request
Let's investigate adding [this mod](https://www.curseforge.com/minecraft/mc-mods/alchemistry) to see if it fits.

What problem does your feature solve?

We've just removed a handful of tech related mods. We don't want to severely imbalance the pack where there are far less tech mods compared to magic mods.

**Comment by Dark-Arcana** [comment]
Apparently [this](https://www.curseforge.com/minecraft/mc-mods/chemlib) adds the chemistry without any of the other stuff.

**Comment by iarspider** [comment]
IMO, this doesn't fit with the theme of the pack. This is a very _niche_ mod, in the same category as Ex Nihilo or RPG (LOTR, pokemon-like, ...) ones.

**Comment by Dark-Arcana** [comment]
I agree. This was put here because we were discussing a bunch of unique tech related mods in an effort to find something that fit. Each suggestion I added was quite different. We settled on adding PneumaticCraft. I'll close this.
