### ISSUE TITLE
Remove Additional Enchanted Miner

### ISSUE THREAD

**Issue by Timbroglio** [SmashingModsTogether/SMT-Issues#53]
**What problem does your feature solve?**
Mod makes big ugly holes, can cause server issues when running near bodies of water. Multiple other mods add options for ore collection that produce less lag and are less destructive overall.

**Comment by Dark-Arcana** [comment]
I recall @Flux really wanted this mod to stay. But I'm all for removing it.

**Comment by Dark-Arcana** [comment]
Removed.
