### ISSUE TITLE
Server sleep percent is ignored

### ISSUE THREAD

**Issue by Timbroglio** [SmashingModsTogether/SMT-Issues#54]
**Describe the issue**
The config that sets a specific % of players required to sleep has no effect

**To Reproduce**
1. Have a server with 2+ people on it
2. Set sleep % config to 100%
3. Any 1 player sleeps: Night advances to day

**Comment by Dark-Arcana** [comment]
Morpheus?

**Comment by Timbroglio** [comment]
Yes, something is ignoring Morpheus and advancing time whenever 1 person is sleeping. Make it *really* hard to have a large multiplayer were where everyone is getting attacked by phantoms, so you have to coordinate who the 1 person who gets to sleep each night is, or all enter bed *simultaneously*

**Comment by OldManDorn** [comment]
I would love to see the percentage that its set on work. like 33% or 50%. but as it stands you only need one person sleeping no matter how many are on.

**Comment by Dark-Arcana** [comment]
Charm added a sleep improvements option that is allowing just 1 player to sleep to end the night.

**Comment by Dark-Arcana** [comment]
> I would love to see the percentage that its set on work. like 33% or 50%. but as it stands you only need one person sleeping no matter how many are on.

The percentage using Morpheus is 30%.

**Comment by Dark-Arcana** [comment]
Fixed in new update by disabling Charm's option.
