### ISSUE TITLE
What use is Wolf Armor [and wahtever related mod]

### ISSUE THREAD

**Issue by OldManDorn** [SmashingModsTogether/SMT-Issues#55]
I do not understand the reason at all for wolf armor. wolves/dogs are very very sparse. even if you find one and train it, if you do armor it, can you even take them with you when you fly all around the map at warp speed via various ways? [i.e. can the wolf/dog even keep up?] 
2ndly: unlike all horse armors, you can not cut/melt the wolf armors. as soon as I see them, I auto trashcan them after hitting E. I am also unsure if they get random enchants from whatever mods do that. 
I am sorry for not being as articulate to remember the mods all the time. [whomever wants to make this a bit more clean may do so]

**Comment by Dark-Arcana** [comment]
That's very useful feedback. Wolf armors aren't really all that useful. They come from the revamped wolf mod.

**Comment by Timbroglio** [comment]
We've discussed adding armor recycling recipes in the past. I'd suggest either taking that route, or removing the mod.

**Comment by Dark-Arcana** [comment]
But what do we think is preferred? Removing a mod is good.

**Comment by Timbroglio** [comment]
Honestly, I'd agree with Dorn's comment about tamed wolves not being particularly useful in this pack. A lower-tech, more RP style modpack would get more out of this mod.

**Comment by Dark-Arcana** [comment]
I added it at the time because my son has like 500 tamed wolves. So I thought some people would think it's fun. But he doesn't play this pack since he's only 6 lmao. I'm removing it now.
