### ISSUE TITLE
Half-slab upgrading to better blocks

### ISSUE THREAD

**Issue by OldManDorn** [SmashingModsTogether/SMT-Issues#56]
I have no idea of the mod that does this, but I am able to take prismarine cobble and half slab it, but when I put it back together, it makes the better block. that are other half slabs that 'upgrade' to better blocks, while others work as intended. Tim knows about it and has more details. I just wanted an awareness.

**Comment by Timbroglio** [comment]
Mismatch between the slab-to-block recipes, turns prismarine cobble (fairly common underground block) into prismarine bricks (the rare material used to make Ocean Monuments)

**Comment by Dark-Arcana** [comment]
Is this in reference to my kubejs script? It's automatically making recipes for thousands of blocks. It's possible for one to be wrong based on its name, so I can make a special case for it.

**Comment by Timbroglio** [comment]
I'm assuming it's the script, yeah. I hadn't gone through it to check the exact one yet. I can do that to save you the work if you'd like, lol

**Comment by Dark-Arcana** [comment]
Fixed in next update.

![image](https://user-images.githubusercontent.com/6245904/153099871-992303bf-42cd-49f7-9a7f-687d4ad05180.png)
