### ISSUE TITLE
Fishing for chests?

### ISSUE THREAD

**Issue by OldManDorn** [SmashingModsTogether/SMT-Issues#57]
I am an avid collector for finding all the fish at the various biomes, all that I am missing is the leech [swamps] and the 2 turtles. I have yet to fish them up at all. nor have I seen them spawn. I also have never seen anything other than fish; I have not fished up a single chest or a tin can. 

2ndly: what is the difference for using a worm, vs using a minnow? are there other baits out there and how do I find them? I have built the tackle box and upgraded my hook to the lucky one, I have changed the bobber and line color. 
reason I bring this up is normal Minecraft fishing would net you random junk noticeably enough as well as fish, but all i see are fish.

also: There are some biomes that you fish in and when you pull up your catch, there is nothing. it does all the noise and effects, but no fish, nothing. just the catch mechanic and then nothing.
I would love to tell you the specific biomes, but I could not remember. I don't know if it has anything to do with whether or not fish are allows to spawn in water in certain biomes. 

Also, also: does the 'deepness' of the water have any conditions on the fish you obtain in the water? for example, I have built a relaxing fishpond in the back of my castle, and I seemed to be only catching 3 fish and then after about 12 are there sometimes I would not get a catch. 
I hope any of this helps in some way.

**Comment by Timbroglio** [comment]
For mod-specific questions, please check the specific mod's guides: https://github.com/TeamMetallurgy/Aquaculture/wiki

Leeches and some types of Turtles do not have an in-game entity, they can only be caught by fishing. 
As for the chests and can: this may have been a Fishing Real issue, and that mod has been removed. I have not been able to reproduce any of the errors you're reporting on the latest release. If you do encounter a biome that rewards no fish, please let us know what the name of that biome is.
