### ISSUE TITLE
Fix spartan shields recipes

### ISSUE THREAD

**Issue by Dark-Arcana** [SmashingModsTogether/SMT-Issues#6]
Spartan Shields stone braced shields only accept cobblestone in their recipe rather than the forge tag for cobblestone.

**Comment by Dsmario64** [comment]
[cobblestone_recipes_needing_fixing.txt](https://github.com/SmashingModsTogether/SMT-Issues/files/7494082/cobblestone_recipes_needing_fixing.txt)

List of recipes that need to be edited so that they have the forge tag instead of the cobblestone block.

**Comment by Dark-Arcana** [comment]
I've worked through your list, excluding a few of the extras such as create and blood magic.
