### ISSUE TITLE
Remove Simply Tea / Farmer's Tea

### ISSUE THREAD

**Issue by Timbroglio** [SmashingModsTogether/SMT-Issues#60]
Schools of Magic also adds a teapot with potion effects granted. Redundant.

**Comment by OldManDorn** [comment]
doesnt the simply tea/farmers tea add comfort effects, or neat options for making potion type effects but not needing to have nether unlocked because you can make tea?

**Comment by Timbroglio** [comment]
Farmer's food adds comfort effects. Schools of Magic tea adds a wider variety of potion effects and also does not require Nether access.

**Comment by OldManDorn** [comment]
I stand...educated.

**Comment by Dark-Arcana** [comment]
So should we remove Simply Tea and Farmer's Tea then? I'm fine with doing it if it's redundant.

**Comment by Timbroglio** [comment]
That'd be my suggestion, yes. It's cute and fun, but having two different teapots with identical functionality, or even strictly better functionality, feels a little redundant. We also ran into some issues on my server with players struggling to figure out which mod was needed to complete certain quests.

**Comment by Dark-Arcana** [comment]
Removed.
