### ISSUE TITLE
OMG where is my chocolate?

### ISSUE THREAD

**Issue by OldManDorn** [SmashingModsTogether/SMT-Issues#61]
I have been in many Jungle and Jungle combo biomes. I have not seen the pods for the seeds to make my chocolate....

I don't think you all understand....

I have many new recipes for chocolate; muffins, hot chocolate, milkshakes.... 

BUT I cannot find any to be able to make the most amazing of things in the Minecraft world.... CHOCOLATE. 

seriously though, is it a spawn issue or mod conflict thing? could the mixing of jungle biomes and not having a specific normal Minecraft jungle biome be the reason the pods are not on the trees? I have also tried growing jungle trees in and out of a 'jungle' biome. I have no clue if you are supposed to be able to grow them on tree spawn regardless of what biome it's grown in.

Also, on a slightly unrelated note, mint may also be in short supply, but it is not as HUGE of a problem as no chocolate is. just saying....

**Comment by Timbroglio** [comment]
They're right here, yah goof.
![javaw_6V8hitM2l6](https://user-images.githubusercontent.com/15707879/153087796-c660ae31-c6cd-47a1-ac45-64a54633cf4e.png)
