### ISSUE TITLE
Remove Witchery: Rewitched

### ISSUE THREAD

**Issue by Timbroglio** [SmashingModsTogether/SMT-Issues#62]
Mod is lacking in most features: majority of crafted items either server no purpose, or only provide benefits that are already covered by other, more fully-developed mods.

Might be worth keeping in case of further updates, but considering the last update was 4 months ago with patch notes "Changelog to be added later" I have concerns.

**Comment by Dark-Arcana** [comment]
Agreed. I'll mark this for removal.

**Comment by Dark-Arcana** [comment]
Removed.
