### ISSUE TITLE
Add mod: Spoorn's Dual-Wield

### ISSUE THREAD

**Issue by Timbroglio** [SmashingModsTogether/SMT-Issues#63]
**Describe your feature request**
Adds a dual-weilding enchant to melee:
https://www.curseforge.com/minecraft/mc-mods/spoorns-dual-wield

**What problem does your feature solve?**
Kick more ass if you're not a COWARD who hides behind SHIELDS

**Comment by OldManDorn** [comment]
wait. is that a spoornerism?

**Comment by Timbroglio** [comment]
Get out.

**Comment by OldManDorn** [comment]
can we have spoons that we can enchant with this that I can then swing at while singing at the same time.
SPOONY BARD anyone?

**Comment by Dark-Arcana** [comment]
Can't add, requires fabric. Though keep it in mind.
