### ISSUE TITLE
Add Mod - Awesome Dungeons Nether

### ISSUE THREAD

**Issue by Timbroglio** [SmashingModsTogether/SMT-Issues#64]
**Describe your feature request**
Nether needs some dungeon love. The existing structures are interesting, but the only "dungeons" are the usual Vanilla ones.
https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-nether-forge

**What problem does your feature solve?**
Moar dungeons

**Comment by Dark-Arcana** [comment]
Still a little upset about how the mod dev did the thing.

**Comment by Timbroglio** [comment]
I mean, fair. IMO the nether still needs some love, it's basically the only dimension without really interesting new dungeons - repurposed structures adds some ruined cities and piglin outposts, but not much else.

**Comment by Dark-Arcana** [comment]
Yeah I agree with the sentiment. It's worth investigating.

**Comment by Dark-Arcana** [comment]
Should be simple enough to add. Putting it in next update.
