### ISSUE TITLE
Modded liquids don't have player physics

### ISSUE THREAD

**Issue by Timbroglio** [SmashingModsTogether/SMT-Issues#66]
**Describe the issue**
Modded liquids do not affect movement, can not be swum in, and do not cause drowning.

**To Reproduce**
Place any modded fluid block. Try swimming

**Comment by Timbroglio** [comment]
After some testing, this appears to be a Forge error.

**Comment by Dark-Arcana** [comment]
Are you seeing that outside of our pack?

**Comment by Timbroglio** [comment]
I made an instance with just Forge and Tinkers: slime liquid has no physics.
I made another instance with just Forge and Pneumaticraft: Oil has no physics.

**Comment by Dark-Arcana** [comment]
Interesting. I wonder if the issue has been reported to Forge. I'm worried that if you did, they would close it and say it was the fault of those mods doing something wrong. That might even be true.

**Comment by Timbroglio** [comment]
Since this is a root issue, not a modpack issue, I don't think there's much point in continuing discussion here.
