### ISSUE TITLE
Add Dank storage

### ISSUE THREAD

**Issue by iarspider** [SmashingModsTogether/SMT-Issues#68]
**Describe your feature request**
Could you please add [DankStorage](https://www.curseforge.com/minecraft/mc-mods/dank-storage)? 

**What problem does your feature solve?**
With the gazillion of different cobble/stone/gravel blocks this is a life saver.

**Comment by Dark-Arcana** [comment]
We've always tried to make sure that there aren't too many mods that do basically the same thing. So each niche gets a single mod if possible. In this case, Sophisticated Backpacks has an upgrade that allows it to work very much like how /dank/null storage blocks work. For everything else, you can store your stuff inside of a Refined Storage network.

We don't plan to add this mod, but you can definitely add it on your own. If you need help, pop into the Discord.

**Comment by iarspider** [comment]
Well, I'd object. To replicate Dank functionality with backpack you need:
* Pickup upgrade (advanced even for 1st tier of Dank)
* Void upgrade - to remove excess stone/gravel/...
* Restock upgrade - to keep some stone in inventory in case you need to build a bridge
* Stack upgrade - since each slot in Dank can store multiple stacks

That's 4 upgrade slots - I think you need at least gold-tier backpack to fit them. In my LP I use the backpack mostly to store tools (yeah, belt is cool, but I keep forgetting about it :D ), experience and (recently) energy for my jetpack - that's three slots (tank, XP pump, battery) in use.

Also, dank can sort of replace drawers if you put it into dock and connect to RS system.

Anyway, thanks for considering this mod. I will continue adding it by hand.

**Comment by Dark-Arcana** [comment]
You make some good points. So I will open this to further discussion rather than outright saying no. Thanks for your feedback.

**Comment by JartanFTW** [comment]
I can't really think of any situation where I would prefer to use this mod over a backpack and a Refined Storage system at home. It's a niche, and I'm not included. Other people may find it more useful though.

**Comment by Timbroglio** [comment]
A bit niche, a bit redundant - think this falls into the category of "If its very important to you, you can install it on your own client".
