### ISSUE TITLE
Add Strage Drawers mod

### ISSUE THREAD

**Issue by iarspider** [SmashingModsTogether/SMT-Issues#69]
**Describe your feature request**
Please add [Storage Drawers](https://www.curseforge.com/minecraft/mc-mods/storage-drawers/). 

**What problem does your feature solve?**
This will help storing the gazillion of different stone-like blocks.

**Comment by Dark-Arcana** [comment]
Storage Drawers take up a lot of space and aren't super easy to organize when there are tons and tons of items. For storing large amounts of items and a great number of different types of items, use Refined Storage. You can also add this mod yourself manually if you want to use it.
