### ISSUE TITLE
Bat passive reward

### ISSUE THREAD

**Issue by OldManDorn** [SmashingModsTogether/SMT-Issues#71]
Bat passive reward is a purple question mark for 1st and 10th kills. I'm guessing because of mod removal.

**Comment by Dark-Arcana** [comment]
@Timiryazev Do you know what the rewards were for bats?

**Comment by Timbroglio** [comment]
It was originally Witchery: Wool of Bat. I'll swap it out for the next update.

**Comment by OldManDorn** [comment]
Tool Belt and  Totem of Undying quests also have witchery rewards.

**Comment by OldManDorn** [comment]
Updated the comment to be more focused and related to Bat quest.

**Comment by Timbroglio** [comment]
Fixed in 1.3.1.
