### ISSUE TITLE
Main Menu Full Screen causes window to break

### ISSUE THREAD

**Issue by HolyPoseida** [SmashingModsTogether/SMT-Issues#72]
When I have the game in windowed mode, the main menu appears correctly.

![image](https://user-images.githubusercontent.com/99225980/153730365-4487129a-9775-4861-810a-52b88c68d78b.png)

However, when I click Fullscreen, it breaks the main menu and it looks like the following.

![image](https://user-images.githubusercontent.com/99225980/153730378-9706e5b6-cf56-419e-a102-2e7c9db9b0b7.png)

**Comment by Dark-Arcana** [comment]
I wonder if this has to do with the changes to the main menu that fixed a previous bug. I'll look into it this next week. Thanks for the report.

**Comment by Dark-Arcana** [comment]
I can't replicate this issue. I've tried in a number of ways. But it always works exactly as expected. Can you get anyone else to replicate it?

**Comment by Timbroglio** [comment]
Always happens to me and literally everyone I know XD

**Comment by Timbroglio** [comment]
Resizing the window doesn't break it, but hitting the "full screen window" button instantly breaks the entire UI, leaving the blank screen shown above

**Comment by Timbroglio** [comment]
Fixed in 1.3.1
