### ISSUE TITLE
Dark Gem

### ISSUE THREAD

**Issue by OldManDorn** [SmashingModsTogether/SMT-Issues#73]
The shattered component was removed, but while i have 100% on the quest, it will not give me the rewards. unsure what i can do about it.

**Comment by Timbroglio** [comment]
I slapped a hotfix on the server, the client-side update will be next week.
As for fixing it on the public server, let me know next time you're on, I'll need to manually reset the quest for you.

**Comment by Timbroglio** [comment]
Fixed in 1.3.1.
