### ISSUE TITLE
Typo under passive kill rewards

### ISSUE THREAD

**Issue by OldManDorn** [SmashingModsTogether/SMT-Issues#75]
![poison](https://user-images.githubusercontent.com/99228601/154170422-9de87151-c59e-4b02-8f3e-053b836c47c5.png)

the others dont have the kill label. they just say the name, and then say the 10x name for the 10x one. yes the 10x one has the kill as well on it.

**Comment by Timbroglio** [comment]
Oh whoops. Thanks.

**Comment by Timbroglio** [comment]
Fixed in 1.3.1
