### ISSUE TITLE
Crashing When Leaving End Or Randomly In Overworld

### ISSUE THREAD

**Issue by ThatCatNamedHack** [SmashingModsTogether/SMT-Issues#76]
When I leave the end I crash like half the time, and sometimes I also crash randomly in the overworld. Looking through crash reports has said that rendering something involving simply jetpacks is not rendering properly, but nobody on the server has even touched simply jetpacks yet. I might mention that it has

To try and re-create the crash:
1. Go to the end.
2. Kill the dragon (hard ik)
3. Attempt to leave, repeat steps 1 and 3 until your game dies.
Alternatively:
1. Exist
2.  That's about it.
Alternatively 2:
1. Craft a dislocator and set its position in the overworld.
2. Go to the end.
3. Leave using dislocator.

I was expecting to be teleported back to the overworld and continue on with life, but the game had other plans for me.

Sadly I have no screenshots available, the game decided to close itself.

I run a windows 10, unsure of what java version I was using, the most up-to-date one I think playing on SMT 1.3.1, the mod as far as I can tell is simply jetpacks. 

Crash report time: https://pastebin.com/P4tMs93F

**Comment by Dark-Arcana** [comment]
Crash report shows that it has nothing to do with the end or the translocator. Stack trace is an issue with the keybind handler from simple jetpacks which is using asm to override the keybind handler for the game.

In the event that a class is being overridden by a mod and some other mod isn't aware of the change while either also overriding or using asm, then there can be a crash like this.

It's good to have this documented here. Please try to replicate in different environments and provide those crash reports. We can then report the issue to the mod developer with the best information possible to fix it.

**Comment by JartanFTW** [comment]
I have not experienced this at all, and I've been playing actively with jetpacks doing things (including killing the ender dragon).
I think this issue may be user-specific, or fixed in an newer update, perhaps?

**Comment by Timbroglio** [comment]
Haven't heard of this issue popping in a while, and it was never consistently reproduceable. Unless this becomes epidemic, I think we can close it for now.
