### ISSUE TITLE
Tombs and Keys

### ISSUE THREAD

**Issue by OldManDorn** [SmashingModsTogether/SMT-Issues#77]
During this latest server crash, i was underwater. because of load time back in, i drowned. i do not have a key for my tomb. I do not know if this is a bug or if sometihng else is going on.

UPDATE: apparently it never generated a tomb for my last death. so now i have lost my inventory, but not my backpack. anything i had soulbound was fine.

**Comment by Timbroglio** [comment]
Stand on top of the tomb, sneak-rightclick

**Comment by OldManDorn** [comment]
as my comment said. it never generated a tomb. therefore i have no key generated, therefore i have no tomb to shift click onto.
so my inventory was taken, no tomb was created, no key was created because no tomb was created. i still have my backpack.

**Comment by Timbroglio** [comment]
You said it never generated a KEY. That's completely different.

**Comment by OldManDorn** [comment]
the original comment i edited saying [UPDATE: apparently it never generated a tomb for my last death. so now i have lost my inventory, but not my backpack. anything i had soulbound was fine.]
