### ISSUE TITLE
Recycling Quark's Gold Bars

### ISSUE THREAD

**Issue by iarspider** [SmashingModsTogether/SMT-Issues#79]
**Describe your feature request**
Quark add Gold Bars (like good ol' Iron Bars, but made of gold) and uses them as windows in the Nether Fortresses. I'd like to request a recipe to recycle these, similar to how you can recycle iron bars.

**What problem does your feature solve?**
There is never "too much gold"

**Implementation**
KubeJS script to smelt gold bar to gold nuggets

**Screenshots**
Similar to this, but for gold bars:

https://cdn.discordapp.com/attachments/874476120819511296/946431836152791090/unknown.png

**Comment by Timbroglio** [comment]
Ooh thanks, totally forgot about this one on the latest update. I'll make sure it gets in to the next one.

**Comment by Timbroglio** [comment]
Fixed in 1.3.3.
