### ISSUE TITLE
Ranged Pumps Mod turning blocks to stone

### ISSUE THREAD

**Issue by ResonantFlux1** [SmashingModsTogether/SMT-Issues#8]
The Ranged Pumps Mod by default turns any blocks it picks up into stone. This can be very annoying when it's not wanted. The setting is changed in \Smashing Mods Together\saves\WorldName\serverconfig/rangedpumps-server.toml

**Comment by Dark-Arcana** [comment]
The purpose of this is to reduce lag by not spawning in a ton of flowing water blocks. But for now, I will disable the replacement and we can see if that causes too much lag. It can be reverted later.
