### ISSUE TITLE
Add Phi mod (Psi addon)

### ISSUE THREAD

**Issue by iarspider** [SmashingModsTogether/SMT-Issues#80]
**Describe your feature request**
Add [Phi](https://www.curseforge.com/minecraft/mc-mods/phi). 

**What problem does your feature solve?**
It adds more tricks, and it's very often used in spells from [Psi spell compendium](https://www.reddit.com/r/psispellcompendium/) subreddit

**Implementation**
> Does it require a new mod or something to be added? 

Yes

**Comment by JartanFTW** [comment]
I like the [Vector Storage Unit](https://github.com/gdavid04/phi/wiki/Vector-Storage-Unit), so as long as there isn't any conflicts or known big bugs with the mod, I'm all for it.

**Comment by Timbroglio** [comment]
Tbh, I can't help but feel that Psi is already a one-stop-shop solution for 99% of the modpack's challenges. I'm concerned this will make Psi the best possible option, rather than just one of many options.

**Comment by JartanFTW** [comment]
> Tbh, I can't help but feel that Psi is already a one-stop-shop solution for 99% of the modpack's challenges. I'm concerned this will make Psi the best possible option, rather than just one of many options.

While I understand where you're thinking of, I disagree about how powerful Psi is.
Psi is phenomenal as an early-game universal tool and for basic defence/transportation, but as you progress- other mods start taking over. This means it **optionally** takes away a lot of the early-game grind that many (including myself!) abhor.

From a psi 'flight' (more like spawning ghost blocks beneath you) spell I move onto jetpacks once I can afford them.
From a psi 3x3 mine spell I moved onto a pickaxe with vein miner + other enchants.
Etc. etc.

I also think it's important to remember that we're trying to make the pack fun, not grindy. There isn't anything added by Phi I see that would allow for more powerful spells, just simply 'new' spells. The absolute most powerful thing imo added by Phi is the [Magic Processing Unit](https://github.com/gdavid04/phi/wiki/Magic-Processing-Unit).

Of course this is just my perspective on it, and it's certainly a biased one as I am an avid Psi user.

**Comment by Dark-Arcana** [comment]
All I need to know is if adding this mod would require adding quests.

**Comment by ThatCatNamedHack** [comment]
You would have to send Tim back to work, but there isn't much that is changed/new so it wouldn't take long.

**Comment by JartanFTW** [comment]
Yeah, it'll need some more quests but Psi quests are super straight forward to make based on our current quests for it.

**Comment by Timbroglio** [comment]
After a bit of experimenting, this mod doesn't seem to add any features that aren't already available through other mods, and this pack is designed to be "beginner friendly" - Psi is already the most "unfriendly" mod we've got, I wouldn't want to overcomplicate it.
