### ISSUE TITLE
Recipe for Binding Card (Dimensional)

### ISSUE THREAD

**Issue by JartanFTW** [SmashingModsTogether/SMT-Issues#81]
**Describe your feature request**
Recipe for Binding Card (Dimensional) from Powah
Should simply be a Binding Card + an ender pearl.

**What problem does your feature solve?**
To get a dimensional binding card currently, you need to right click with a binding card on an enderman. This fails, as you also must right click in order to bind the binding card to yourself, which takes priority.

**Implementation**
Simply add a recipe, so I don't need to go through this hell. As far as I'm aware, you cannot un-bind a binding card once bound.

**Comment by iarspider** [comment]
@JartanFTW Worked for me just a few days ago.

**Comment by JartanFTW** [comment]
> @JartanFTW Worked for me just a few days ago.

It works, yes, but it takes many tries sometimes and as you can't un-bind, you're just making extra cards you'll never use. At least I struggle with it...

**Comment by Timbroglio** [comment]
Testing this: you can use a binding card that's bound to you on an endermen, to make a dimensional binding card that's bound to you. Is there a strong need to make unbound dimension binding cards?

**Comment by JartanFTW** [comment]
> Testing this: you can use a binding card that's bound to you on an endermen, to make a dimensional binding card that's bound to you. Is there a strong need to make unbound dimension binding cards?

Ok, then this just doesn't work for me and I don't know why.

I've spent a good 15+ minutes just trying to get a single dimensional binding card, and the already bound ones def don't do anything for me when I click on an eman with em.

I still think we should just add a simple recipe as an alternative, as it doesn't really harm anything anyway.

Next time I'm ingame, I'll play around with this a bit more.

**Comment by Timbroglio** [comment]
Even if working in-game is fine, I don't see a strong reason not to add an option for crafting it.
Added in 1.3.4
