### ISSUE TITLE
4096k Storage Part Quest doesn't Fire Completion

### ISSUE THREAD

**Issue by JartanFTW** [SmashingModsTogether/SMT-Issues#82]
**Describe the issue**
4096k Storage Part Quest doesn't Fire Completion

**To Reproduce**
1. Complete all prerequisite quests.
2. Craft a 4096k Storage Part from extradisks:4096k_storage_part

**Expected behavior**
The quest should fire as completed in the quest book.

**Screenshots**
![image](https://user-images.githubusercontent.com/66337180/155873133-c794899c-79fc-46d9-8b48-0c09ff54c82c.png)
![image](https://user-images.githubusercontent.com/66337180/155873141-7f1615b7-a2a5-41b2-aff2-ce9ec94ab2e5.png)

**Additional context**
To solve this, make the quests complete for extradisks also. Currently quests seem to support either extrastorage or extradisks, but not both.

**Comment by Timbroglio** [comment]
Brute-forced a fix, will be in 1.3.3.
This quest might still be bugged for you personally, just craft another 4096k part to clear it.

This fix might break auto-crafting systems, which will need to be fixed by re-setting the crafting recipe.
