### ISSUE TITLE
Alternative pipe mod

### ISSUE THREAD

**Issue by iarspider** [SmashingModsTogether/SMT-Issues#84]
**Describe your feature request**
As discussed in Discord, pipes from Refined Pipes are stupid and will drop items in world if they can't insert them into inventory. We can consider one (or more) of the following mods as a more reliable altenative:

* [Pipez](https://www.curseforge.com/minecraft/mc-mods/pipez)
* [Xnet](https://www.curseforge.com/minecraft/mc-mods/xnet)
* [Modular routers](https://www.curseforge.com/minecraft/mc-mods/modular-routers)
* [Pedestals](https://www.curseforge.com/minecraft/mc-mods/pedestals)
* [Integrated Dynamics](https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics) + [Integrated Tunnels](https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels) - some may consider adding this mod just for pipes an overkill...

**What problem does your feature solve?**
Leaky Refined Pipes

**Implementation**
> Does it require a new mod or something to be added?

Yes

**Comment by JartanFTW** [comment]
My take:

Pipez looks good, however apparently was used in previous versions of SMT and didn't play well with other mods.

Xnet looks like a developers dream. It looks like you could do everything and anything with it, but the interface looks extremely difficult to learn.

Modular Routers looks extremely useful as just a catch-all fallback gadget that I'd love to see implemented in SMT. Despite this, I don't think that this is a good 'replacement' for a pipe mod, as this does take a whole lot of visual aspects out of building systems which many may not like.

Pedestals offer an alternative using a sort of magic theme, but we're trying to replace an engineering mod and should probably stick to the same theme. Along with this, pedestals seem to just be a similar idea to Modular Routers, but more 'fancy' leading to more clunk and likely lag. I could be wrong, this is the only one I'm not looking at too in-depth.

Integrated Dynamics I think is overkill. I'd rather not have it.

**Comment by castillao** [comment]
My opinion regarding xnet as a pipe alternative:

i was taking a look at this video for the https://www.youtube.com/watch?v=ksaJgiipaOg  xnet mod for the pipe discussion, and im kinda not convinced
* having a RF consuming controller needed to transport i think is not a nice replacement for a controllerless pipe system
* the controller seem to only allow 8 channels which seems like it could be annoying when connecting up all your base
* having a controller+channel system seems too similar to refined storage (or AE2)

**Comment by iarspider** [comment]
We are not talking about replacing Refined Pipes - they are good for simple transport, especially for transporting fluids. Item transport is also ok if the receiving end can't overflow (e.g. a trashcan 😛). And I'd consider them "essential" for the pack, since removing them will break... just about every automation in players' worlds.

@castillao 

> * having a RF consuming controller needed to transport i think is not a nice replacement for a controllerless pipe system
RF usage is optional and can be disabled in config

> * the controller seem to only allow 8 channels which seems like it could be annoying when connecting up all your base
>  * having a controller+channel system seems too similar to refined storage (or AE2)
* While this may seem similar to RS/AE2, it's not RS/AE2 replacement (ID+IT could replace RS/AE2, but it's hard and painful to use it this way - even for advanced players). It's more of a local (one controller per task) routing than storage system - and the controllers are not too expensive (only slightly more expensive than RS one, IIRC)

@JartanFTW 

> Xnet looks like a developers dream. It looks like you could do everything and anything with it, but the interface looks extremely difficult to learn.

IMHO, it's "easy to learn, difficult to master" type of mod. You can just learn the basics and use them, and only touch high level stuff if you really need (which is rare and often easier to accomplish using other mods)

**Comment by JartanFTW** [comment]
I'm interested in hearing @Dark-Arcana and @Timiryazev' thoughts on these mods.

**Comment by Dark-Arcana** [comment]
It's certainly possible for us to add or change the mods for pipes. However, that can't be done by update time tomorrow as it will require changing quests, testing, etc. How about we schedule this for next week's update?

**Comment by Timbroglio** [comment]
1.3.4 will include Pretty Pipes. Please try these out and see if they're more to your liking ^^
