### ISSUE TITLE
(Quark) Soul beads not obtainable

### ISSUE THREAD

**Issue by iarspider** [SmashingModsTogether/SMT-Issues#85]
**Describe the issue**
Quark's Soul beads (a drop from Quark's Wraiths) are required for one of the quests, but are not obtainable since Wraiths are disabled in config.

**To Reproduce**
1. Go to souls sand biome in the Nether
2. Wait for Wraiths to spawn
3. Observe 0 wraiths spawn for several IRL hours

**Expected behavior**
Tons of wraiths and tons of beads from them

**Screenshots**
N/A

**Game Environment(please complete the following information):**
- Operating System Windows 10
- Java Version 8.0.312.7
- Modpack Version 1.3.3
- Mod causing issue if applicable Quark

**Additional context**
Either re-enable Wraiths in config, or add a recipe to get these beads (e.g. pulverizing soul soil?)

**Comment by Timbroglio** [comment]
...I'm pretty sure Arcana disabled the Quark wraiths because he assumed they'd overlap with the Eidolon wraiths. I'm testing with the configs a bit to see if I can get them spawning at a reasonable rate.

**Comment by Dark-Arcana** [comment]
This is correct. I tried to not have a lot of overlapping. There were also wraiths from dungeons mobs. And I didn't know the ones from quark dropped anything (so that's my bad). So we can re-enable all wraiths and hope to find the ones you need lol, or we can make some recipes for the items you might want from drops with a quest noting that change.

**Comment by Timbroglio** [comment]
After a bit of testing, it seems like limiting wraiths to Soul Sand Valleys works fine, without the need for adding more refined spawn rules. They're still a fairly rare spawn, but their Beads are a 100% drop rate, so it should be fine.
Fix will be included in 1.3.4.
