### ISSUE TITLE
Shrink ray not obtainable?

### ISSUE THREAD

**Issue by iarspider** [SmashingModsTogether/SMT-Issues#87]
**Describe the issue**
There is no recipe for Shrink ray (from Shrink mod), and it is required for one of the quests.

**To Reproduce**
1. Go to JEI
2. Look for a way to get Shrink ray
3. See nothing

**Expected behavior**
Either a recipe to make one, or some description of where to find it

**Screenshots**
N/A

**Game Environment(please complete the following information):**
- Operating System **Windows 10**
- Java Version **1.8.0_312-b07**
- Modpack Version **1.3.3**
- Mod causing issue if applicable **Shrink**

**Comment by Timbroglio** [comment]
I think it's supposed to be dungeon loot, but frankly I've never found one. For now, going to remove the quest requirement.

**Comment by Timbroglio** [comment]
Fixed in 1.3.4, re-enabled the quest.
