### ISSUE TITLE
External Storage Quest Typo

### ISSUE THREAD

**Issue by JartanFTW** [SmashingModsTogether/SMT-Issues#88]
**Describe the issue**
There is a typo in the External Storage quest where "barrel" is written as "barrely".

**Screenshots**
![image](https://user-images.githubusercontent.com/66337180/158029230-273e41e4-37f7-47bb-b34e-c13605a527fa.png)

**Game Environment(please complete the following information):**
- Modpack Version : 1.3.4

**Comment by Timbroglio** [comment]
Fixed, thanks!
