### ISSUE TITLE
EvilCraft blood spots break tinker's construct structures

### ISSUE THREAD

**Issue by JartanFTW** [SmashingModsTogether/SMT-Issues#89]
**Describe the issue**
Tinker's Construct is designed in a way that intends for the player to kill mobs using the Smeltery and Foundry. On occasion, EvilCraft (I think) blood spatters can form from even the smallest of player intervention in the mob's death, which then breaks the smeltery and foundry.

**To Reproduce**
1. Build a smeltery
2. Add a spawner right above the smeltery.
3. Hit mobs until blood spatters spawn inside the smeltery.

**Desired behavior**
Blood spatters should not form on any tinkers construct blocks, especially seared and scorched blocks.

**Game Environment(please complete the following information):**
- Modpack Version : 1.3.4
- Mod causing issue if applicable : EvilCraft

**Comment by Dark-Arcana** [comment]
Based on your description, this is an issue with the two mods not made to work together. It would make sense then to cross-post this issue to a new issue in the EvilCraft GitHub. Before doing that, make sure you can replicate this issue in a new profile with just those two mods. I can help you make the other issue if you'd like, but I figured you'd be alright with it.

**Comment by Timbroglio** [comment]
Blood splatters should only form when the cause of death is falling, which might happen if your smeltery is tall enough and you're knocking mobs into it.

I don't think there's any way to blacklist exactly which blocks bloodstains can form on.

I'd suggest putting a Sanguinary Pedestal underneath your smeltery, that fixes it.

**Comment by Dark-Arcana** [comment]
Ahh perfect. No need to open a new issue if there's already a solution. Might want to make a quest about it somewhere?

**Comment by Timbroglio** [comment]
There's already a quest for the Pedestal. It's explicitly described as a tool who's purpose is to automatically remove & collect bloodstains.

**Comment by Dark-Arcana** [comment]
That's perfect. Then there's nothing that needs to be done but tell Jartan to read the book lmao.
