### ISSUE TITLE
Add Mosaic Blocks Mod

### ISSUE THREAD

**Issue by LickenMicks** [SmashingModsTogether/SMT-Issues#90]
**Describe your feature request**
Add Mosaic Blocks to the modpack

**What problem does your feature solve?**
Adds dyable mosaic blocks

**Implementation**
Add a new mod, Mosaic Blocks, to the modpack [https://www.curseforge.com/minecraft/mc-mods/mosaic-blocks/screenshots](url)

**Screenshots**
See mod curseforge page (link above)

**Comment by Dark-Arcana** [comment]
Added in 1.3.5.
